### ISSUE TITLE
Real time database on firebase

### ISSUE THREAD

**Issue by peyman-hakemi** [saalikmubeen/whatsApp-lite#2]
Hi, first of all THANK YOU for your great work. we used your source in our project. but we have a problem with the Real time database rules.
every day firebase will email us, and says our rules are not secure. do you have any suggestion or rule example that we can use in our firebase project that will secure our databse?

**Comment by saalikmubeen** [comment]
Hey. I’m really glad you found it useful.  Firebase has certain database rules that you can implement. Firebase lets you run the database in test mode. Make you sure you set it to production. 

To enhance the security of your Firebase project, you can consider implementing rules that restrict access based on user authentication and only allow authorized users to read or write data. Here's a basic example for a Firebase Realtime Database rule:

```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

This simple rule ensures that only authenticated users can read and write data. But there is a catch to it. It’ll lock read and writes to your entire database meaning user who is coming to sign up or login won’t be able to do so since they won’t be authenticated when trying to sign up. You can modify the rules to restrict access to only certain parts of the database. You can read more on Firebase rules and how the syntax works and how you can custom it to fit your application needs. 

You can read more on it here:
https://firebase.google.com/docs/database/security/core-syntax

Hope it helps :)
